name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          
    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Clippy
      run: cargo clippy --tests --all-features --manifest-path broken_url_finder
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt
    - name: Run tests
      run: cargo test --verbose
